### ISSUE TITLE
ebean-components update for ebean 16

### ISSUE THREAD

**Issue by serhii-bondar** [ebean-orm/ebean-components#3]
Hello,

I hope you’re doing well.
I wanted to ask if there are any plans to update the Ebean components to support Ebean 16. Currently, it seems that the query autotune component is not compatible.

I encountered the following issue:

java.lang.NoSuchMethodError: 'io.ebeaninternal.server.querydefn.OrmQueryDetail io.ebeaninternal.server.querydefn.OrmQueryDetail.copy()'
	at io.ebeaninternal.server.autotune.service.TunedQueryInfo.tuneQuery(TunedQueryInfo.java:55)
	at io.ebeaninternal.server.autotune.service.BaseQueryTuner.tuneQuery(BaseQueryTuner.java:125)
	at io.ebeaninternal.server.autotune.service.DefaultAutoTuneService.tuneQuery(DefaultAutoTuneService.java:292)
	at io.ebeaninternal.server.core.DefaultServer.buildQueryRequest(DefaultServer.java:950)
	at io.ebeaninternal.server.core.DefaultServer.findId(DefaultServer.java:1030)
	at io.ebeaninternal.server.core.DefaultServer.findOne(DefaultServer.java:1053)
	at io.ebeaninternal.server.core.DefaultServer.findOneOrEmpty(DefaultServer.java:1045)
	at io.ebeaninternal.server.querydefn.DefaultOrmQuery.findOneOrEmpty(DefaultOrmQuery.java:1604)

Could you please let me know if there are plans to release an update or if there’s a recommended workaround for this compatibility issue?

Thank you for your time and assistance.

**Comment by rbygrave** [comment]
This was an issue introduced by https://github.com/ebean-orm/ebean/pull/3673 ... version `16.1.0`

**Comment by rbygrave** [comment]
Deployed version 16.1.0 of these components, and those will support version 16.1.0+.
